config/routes.rb
Rails.application.routes.draw do
  resources :settings

  root 'settings#index'

end

app/models/setting.rb
class Setting < ActiveRecord::Base
  validates :name,  presence: true
end

app/models/store_setting.rb
class StoreSetting < ActiveRecord::Base
  validates :name,  presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/settings_controller.rb
class SettingsController < ApplicationController
  before_action :set_setting_from, only: [:show, :edit, :update, :destroy]

  # GET /settings
  def index
    @settings = Setting.all
    @store_settings = StoreSetting.all
  end

  # GET /settings/1
  def show
  end

  # GET /settings/new
  def new
    @form = SettingForm.new
    @form.setting = Setting.new
    @form.store_setting = StoreSetting.new
  end

  # GET /settings/1/edit
  def edit
  end

  # POST /settings
  def create
    @form = SettingForm.new
    @form.receive(setting_form_params)

    if @form.valid?
      service = @form.build_create_service
      service.execute!
      redirect_to settings_url, notice: 'Setting was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /settings/1
  def update
    @form.attributes(setting_form_params)
    if @form.valid?
      service = @form.build_update_service
      service.execute!
      redirect_to settings_url, notice: 'Setting was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /settings/1
  def destroy
    service = @form.build_destroy_service
    service.execute!
    redirect_to settings_url, notice: 'Setting was successfully destroyed.'
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_setting_from
    @form = SettingForm.new()
    @form.setting = Setting.find(params[:id])
    @form.store_setting = StoreSetting.first # 固定
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def setting_form_params
    params.require(:setting_form).permit(setting: [:name], store_setting: [:store_name, :name])
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/settings_helper.rb
module SettingsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>MultipleModelsSample</title>
  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<header class="navbar navbar-inverse" role="navigation">
  <div class="navbar-inner">
    <div class="container">
      <div class="navbar-header">
        <a class="navbar-brand" href="#">MultipleModelsSample</a>
      </div>
    </div>
  </div>
</header>
<div class="container master-container">
  <% if notice %>
    <div class="alert alert-success fade in" data-alert="alert">
      <a class="close" data-dismiss='alert' href="#">×</a>

      <p><%= notice %></p>
    </div>
  <% end %>

  <%= yield %>
</div>
</body>
</html>

app/views/settings/_form.html.slim
= simple_form_for(@form, html: {class: 'form-horizontal'}, url: @form.url, method: @form.method) do |f|
  = f.error_notification

  = f.fields_for @form.setting do |setting_form|
    .form-inputs
      = setting_form.input :name

  = f.fields_for @form.store_setting do |store_setting_form|
    .form-inputs
      = store_setting_form.input :store_name
      = store_setting_form.input :name

  .form-actions
    = f.button :submit

app/views/settings/edit.html.slim
h1 Editing setting

== render 'form'

= link_to 'Show', @setting
'|
= link_to 'Back', settings_path

app/views/settings/index.html.slim
h1 Listing settings

table
  thead
    tr
      th Name
      th
      th
      th

  tbody
    - @settings.each do |setting|
      tr
        td = setting.name
        td = link_to 'Show', setting
        td = link_to 'Edit', edit_setting_path(setting)
        td = link_to 'Destroy', setting, data: {:confirm => 'Are you sure?'}, :method => :delete

br

= link_to 'New Setting', new_setting_path

br
hr

h1 Listing Store settings

table
  thead
    tr
      th Store Name
      th Name

  tbody
    - @store_settings.each do |setting|
      tr
        td = setting.store_name
        td = setting.name
br

app/views/settings/new.html.slim
h1 New setting

== render 'form'

= link_to 'Back', settings_path

app/views/settings/show.html.slim
p#notice = notice

p
  strong Name:
  = @form.setting.name

/= link_to 'Edit', edit_setting_path(@setting)
/'|
/= link_to 'Back', settings_path